import { Decision, Signal, Pod, ClosedDecision } from "./types";

export const decisions: Decision[] = [
  {
    id: "d1",
    title: "Realign enterprise pricing tier",
    triggerSignal: "Enterprise NRR dropped 4pts in Q4",
    outcomeTarget: "Restore NRR to 115% within 60 days",
    outcomeCategory: "Revenue",
    expectedImpact: "+4pts NRR",
    currentDelta: "+1.2pts (gap: 2.8pts)",
    revenueAtRisk: "$2.4M ARR",
    impactTier: "High",
    segmentImpact: "Enterprise",
    owner: "Sarah Chen",
    status: "Active",
    createdDate: "2026-02-01",
    sliceDeadlineDays: 10,
  },
  {
    id: "d2",
    title: "Consolidate agent routing logic",
    triggerSignal: "Agent resolution variance exceeded 18%",
    outcomeTarget: "Reduce variance to <8% across all segments",
    outcomeCategory: "Agent Performance",
    expectedImpact: "-10pts variance",
    currentDelta: "-4pts (gap: 6pts)",
    impactTier: "High",
    owner: "Marcus Webb",
    status: "Active",
    createdDate: "2026-02-03",
    sliceDeadlineDays: 10,
  },
  {
    id: "d3",
    title: "Launch self-serve onboarding for SMB",
    triggerSignal: "SMB activation rate at 31%, target 55%",
    outcomeTarget: "Hit 50% activation within 30 days of launch",
    outcomeCategory: "Conversion",
    expectedImpact: "+19pts activation",
    currentDelta: "+5pts (gap: 14pts)",
    revenueAtRisk: "$890K pipeline",
    impactTier: "High",
    segmentImpact: "SMB",
    owner: "Priya Patel",
    status: "Active",
    createdDate: "2026-02-05",
    sliceDeadlineDays: 10,
  },
  {
    id: "d4",
    title: "Deprecate legacy analytics module",
    triggerSignal: "Maintenance cost 3x of replacement",
    outcomeTarget: "Zero legacy dependencies by March 15",
    outcomeCategory: "Efficiency",
    expectedImpact: "-67% maintenance cost",
    currentDelta: "-12% (gap: 55%)",
    impactTier: "Medium",
    owner: "James Liu",
    status: "Blocked",
    createdDate: "2026-02-04",
    sliceDeadlineDays: 10,
    blockedReason: "Downstream API consumers not yet migrated",
    blockedDependencyOwner: "Platform Team (Yuki Tanaka)",
  },
  {
    id: "d5",
    title: "Hire VP of Revenue Operations",
    triggerSignal: "RevOps function has no owner",
    outcomeTarget: "Signed offer by Feb 28",
    outcomeCategory: "Efficiency",
    expectedImpact: "RevOps function operational",
    impactTier: "High",
    owner: "CEO",
    status: "Active",
    createdDate: "2026-01-28",
    sliceDeadlineDays: 10,
  },
  {
    id: "d6",
    title: "Migrate payment processor",
    triggerSignal: "Current processor fee increase of 40bps",
    outcomeTarget: "Migration complete, zero downtime",
    outcomeCategory: "Revenue",
    expectedImpact: "-40bps processing cost",
    revenueAtRisk: "$340K annual savings",
    impactTier: "Medium",
    owner: "Alex Torres",
    status: "Draft",
    createdDate: "2026-02-12",
    sliceDeadlineDays: 10,
  },
  {
    id: "d7",
    title: "Renegotiate cloud infrastructure contract",
    triggerSignal: "Annual renewal approaching with 22% overspend",
    outcomeTarget: "Reduce annual cloud spend by 15%",
    outcomeCategory: "Efficiency",
    expectedImpact: "-15% cloud spend",
    currentDelta: "-3% (gap: 12%)",
    revenueAtRisk: "$1.1M annual",
    impactTier: "High",
    segmentImpact: "Infrastructure",
    owner: "Marcus Webb",
    status: "Active",
    createdDate: "2026-02-06",
    sliceDeadlineDays: 10,
  },
];

export const signals: Signal[] = [
  {
    id: "s1",
    type: "KPI Deviation",
    description: "Customer support CSAT dropped below 82% threshold",
    source: "Support Analytics",
    createdDate: "2026-02-14",
  },
  {
    id: "s2",
    type: "Segment Variance",
    description: "Mid-market churn rate 2.1x higher than enterprise",
    source: "Revenue Team",
    createdDate: "2026-02-13",
  },
  {
    id: "s3",
    type: "Agent Drift",
    description: "Agent response consistency score below 70% in APAC",
    source: "Agent Monitoring",
    createdDate: "2026-02-14",
  },
  {
    id: "s4",
    type: "Launch Milestone",
    description: "V3 API beta ready for controlled rollout",
    source: "Platform Team",
    createdDate: "2026-02-12",
  },
  {
    id: "s5",
    type: "Exec Escalation",
    description: "Board requesting updated GTM timeline",
    source: "CEO Office",
    createdDate: "2026-02-15",
  },
];

export const pods: Pod[] = [
  {
    id: "p1",
    name: "Growth Pod",
    owner: "Priya Patel",
    initiatives: [
      { id: "i1", name: "SMB self-serve onboarding", lastDemoDate: "2026-02-10", sliceDeadline: "2026-02-20", owner: "Priya Patel", outcomeLinked: true, shipped: false },
      { id: "i2", name: "Referral program v2", lastDemoDate: undefined, sliceDeadline: "2026-02-18", owner: "Dan Kim", outcomeLinked: false, shipped: false },
    ],
  },
  {
    id: "p2",
    name: "Platform Pod",
    owner: "Marcus Webb",
    initiatives: [
      { id: "i3", name: "Agent routing consolidation", lastDemoDate: "2026-02-08", sliceDeadline: "2026-02-22", owner: "Marcus Webb", outcomeLinked: true, shipped: false },
      { id: "i4", name: "V3 API beta", lastDemoDate: "2026-02-12", sliceDeadline: "2026-02-19", owner: "Yuki Tanaka", outcomeLinked: true, shipped: true },
    ],
  },
  {
    id: "p3",
    name: "Revenue Pod",
    owner: "Sarah Chen",
    initiatives: [
      { id: "i5", name: "Enterprise pricing realignment", lastDemoDate: "2026-02-06", sliceDeadline: "2026-02-16", owner: "Sarah Chen", outcomeLinked: true, shipped: false },
      { id: "i6", name: "Contract automation", sliceDeadline: "2026-02-25", owner: "Raj Mehta", outcomeLinked: false, shipped: false },
    ],
  },
];

export const closedDecisions: ClosedDecision[] = [
  {
    id: "cd1",
    decisionId: "d-old-1",
    title: "Reduce trial-to-paid friction",
    expectedOutcome: "Increase trial conversion from 12% to 20%",
    actualResult: "Conversion reached 18.4% — partial success",
    segmentShift: "SMB conversion +8pts, Enterprise flat",
    notes: "Checkout redesign had largest impact. Credit card requirement removal was key lever.",
    closedDate: "2026-01-20",
  },
  {
    id: "cd2",
    decisionId: "d-old-2",
    title: "Restructure CS team by segment",
    expectedOutcome: "Improve CSAT by 10pts across all segments",
    actualResult: "Enterprise CSAT +12pts, SMB +4pts",
    agentImpact: "Agent specialization reduced escalation rate by 35%",
    notes: "SMB segment needs dedicated onboarding support. Enterprise restructure exceeded targets.",
    closedDate: "2026-01-15",
  },
];
