import { Decision, Signal, Pod, ClosedDecision } from "./types";

export const decisions: Decision[] = [
  {
    id: "d1",
    title: "Stabilize live event buffering variance for Tier-1 streaming client",
    triggerSignal: "QoE degradation detected during peak live events — buffering ratio 2.3x above SLA",
    outcomeTarget: "Restore buffering ratio to <0.5% within 30 days",
    outcomeCategory: "QoE Risk",
    expectedImpact: "-65% buffering variance",
    currentDelta: "-18% (gap: 47%)",
    revenueAtRisk: "$4.8M ARR renewal exposure",
    impactTier: "High",
    segmentImpact: "Enterprise — Tier-1 Streaming",
    owner: "Sarah Chen",
    status: "Active",
    createdDate: "2026-02-01",
    sliceDeadlineDays: 10,
    solutionType: "S1",
    surface: "Video Insights",
    decisionHealth: "At Risk",
  },
  {
    id: "d2",
    title: "Consolidate Agent Outcome scoring logic across segments",
    triggerSignal: "Agent resolution variance exceeded 18% across enterprise client base",
    outcomeTarget: "Reduce scoring variance to <8% across all enterprise segments",
    outcomeCategory: "Agent Trust",
    expectedImpact: "-10pts variance",
    currentDelta: "-4pts (gap: 6pts)",
    revenueAtRisk: "$2.1M upsell tied to Agent adoption",
    impactTier: "High",
    owner: "Marcus Webb",
    status: "Active",
    createdDate: "2026-02-03",
    sliceDeadlineDays: 10,
    solutionType: "S3",
    surface: "Agent Intelligence",
    decisionHealth: "Degrading",
  },
  {
    id: "d3",
    title: "Reduce mid-market DPI pattern false positives in e-commerce vertical",
    triggerSignal: "DPI false positive rate at 14%, eroding mid-market confidence",
    outcomeTarget: "Reduce false positive rate to <5% within 45 days",
    outcomeCategory: "Platform Adoption",
    expectedImpact: "-9pts false positive rate",
    currentDelta: "-3pts (gap: 6pts)",
    revenueAtRisk: "$1.6M pipeline at risk",
    impactTier: "High",
    segmentImpact: "Mid-Market — E-Commerce",
    owner: "Priya Patel",
    status: "Active",
    createdDate: "2026-02-05",
    sliceDeadlineDays: 10,
    solutionType: "S2",
    surface: "DPI",
    decisionHealth: "On Track",
  },
  {
    id: "d4",
    title: "Reposition VDPI as transitional bridge to DPI",
    triggerSignal: "M&E strategy misalignment — VDPI and DPI positioning overlap in renewal conversations",
    outcomeTarget: "Unified positioning narrative approved by GTM leadership",
    outcomeCategory: "Executive Credibility",
    expectedImpact: "Eliminate positioning conflict",
    currentDelta: "Draft narrative in review",
    impactTier: "Medium",
    owner: "James Liu",
    status: "Blocked",
    createdDate: "2026-02-04",
    sliceDeadlineDays: 10,
    blockedReason: "GTM leadership alignment pending — conflicting renewal narratives across regions",
    blockedDependencyOwner: "GTM & Positioning Pod (VP Marketing)",
    solutionType: "Cross-Solution",
    surface: "GTM Strategy",
    decisionHealth: "Degrading",
  },
  {
    id: "d5",
    title: "Establish executive-facing Agent Trust Index",
    triggerSignal: "No standardized trust metric for agent performance in production — board requesting clarity",
    outcomeTarget: "Agent Trust Index defined, validated, and presented to board",
    outcomeCategory: "Agent Trust",
    expectedImpact: "Board-ready agent performance metric",
    impactTier: "High",
    owner: "CEO",
    status: "Active",
    createdDate: "2026-01-28",
    sliceDeadlineDays: 10,
    solutionType: "S3",
    surface: "Agent Intelligence",
    decisionHealth: "At Risk",
  },
  {
    id: "d6",
    title: "Align Video Insights narrative with DPI positioning in renewal cycle",
    triggerSignal: "Enterprise renewals surfacing confusion between S1 and S2 value props",
    outcomeTarget: "Unified renewal deck with clear S1→S2 migration narrative",
    outcomeCategory: "Enterprise Renewal",
    expectedImpact: "Reduce renewal friction by 40%",
    revenueAtRisk: "$3.2M renewal pipeline",
    impactTier: "High",
    segmentImpact: "Enterprise",
    owner: "Alex Torres",
    status: "Active",
    createdDate: "2026-02-06",
    sliceDeadlineDays: 10,
    solutionType: "Cross-Solution",
    surface: "GTM Strategy",
    decisionHealth: "At Risk",
  },
  {
    id: "d7",
    title: "Reduce live event escalation latency by 30%",
    triggerSignal: "Escalation response time 2.4x above target during Tier-1 live events",
    outcomeTarget: "Reduce mean escalation latency from 12min to <8min",
    outcomeCategory: "QoE Risk",
    expectedImpact: "-30% escalation latency",
    currentDelta: "-8% (gap: 22%)",
    revenueAtRisk: "$1.9M contract risk",
    impactTier: "Medium",
    segmentImpact: "Enterprise — Streaming Ops",
    owner: "Marcus Webb",
    status: "Draft",
    createdDate: "2026-02-12",
    sliceDeadlineDays: 10,
    solutionType: "S1",
    surface: "Streaming Ops",
    decisionHealth: "On Track",
  },
  {
    id: "d8",
    title: "Standardize outcome attribution across DPI & Agent layers",
    triggerSignal: "No unified attribution model — DPI and Agent outcomes measured in silos",
    outcomeTarget: "Single attribution framework adopted across S2 and S3",
    outcomeCategory: "Platform Adoption",
    expectedImpact: "Unified outcome measurement",
    currentDelta: "Framework design 40% complete",
    impactTier: "Medium",
    owner: "Priya Patel",
    status: "Active",
    createdDate: "2026-02-08",
    sliceDeadlineDays: 10,
    solutionType: "Cross-Solution",
    surface: "DPI / Agent",
    decisionHealth: "On Track",
  },
];

export const signals: Signal[] = [
  {
    id: "s1",
    type: "KPI Deviation",
    description: "Tier-1 streaming client QoE score dropped below 82% SLA threshold during live events",
    source: "Video Insights Platform",
    createdDate: "2026-02-14",
    solutionType: "S1",
  },
  {
    id: "s2",
    type: "Renewal Risk",
    description: "Enterprise renewal pipeline showing 2.1x higher objection rate on DPI value prop",
    source: "Revenue Operations",
    createdDate: "2026-02-13",
    solutionType: "S2",
  },
  {
    id: "s3",
    type: "Agent Drift",
    description: "Agent outcome consistency score below 70% in APAC enterprise deployments",
    source: "Agent Monitoring",
    createdDate: "2026-02-14",
    solutionType: "S3",
  },
  {
    id: "s4",
    type: "Cross-Solution Conflict",
    description: "DPI and Agent Trust metrics producing contradictory signals for same enterprise account",
    source: "Platform Engineering",
    createdDate: "2026-02-12",
    solutionType: "Cross-Solution",
  },
  {
    id: "s5",
    type: "Exec Escalation",
    description: "Board requesting unified transformation timeline — S1 to S3 migration clarity needed",
    source: "CEO Office",
    createdDate: "2026-02-15",
    solutionType: "Cross-Solution",
  },
  {
    id: "s6",
    type: "Segment Variance",
    description: "EMEA enterprise retention 3.2pts below NA — DPI adoption gap widening",
    source: "Regional Analytics",
    createdDate: "2026-02-11",
    solutionType: "S2",
  },
  {
    id: "s7",
    type: "Launch Milestone",
    description: "Agent Trust Index v1 framework ready for executive validation",
    source: "Agent Intelligence Pod",
    createdDate: "2026-02-15",
    solutionType: "S3",
    decisionId: "d5",
  },
];

export const pods: Pod[] = [
  {
    id: "p1",
    name: "Streaming Platform Pod",
    owner: "Sarah Chen",
    solutionType: "S1",
    initiatives: [
      { id: "i1", name: "Live event buffering optimization", lastDemoDate: "2026-02-10", sliceDeadline: "2026-02-20", owner: "Sarah Chen", outcomeLinked: true, shipped: false, renewalAligned: true },
      { id: "i2", name: "Escalation latency pipeline", lastDemoDate: undefined, sliceDeadline: "2026-02-18", owner: "Dan Kim", outcomeLinked: false, shipped: false, renewalAligned: false },
    ],
  },
  {
    id: "p2",
    name: "DPI Platform Pod",
    owner: "Priya Patel",
    solutionType: "S2",
    initiatives: [
      { id: "i3", name: "False positive reduction — e-commerce", lastDemoDate: "2026-02-08", sliceDeadline: "2026-02-22", owner: "Priya Patel", outcomeLinked: true, shipped: false, renewalAligned: true, crossSolutionDep: "Agent Intelligence Pod" },
      { id: "i4", name: "DPI-Agent attribution framework", lastDemoDate: "2026-02-12", sliceDeadline: "2026-02-19", owner: "Raj Mehta", outcomeLinked: true, shipped: true, crossSolutionDep: "Agent Intelligence Pod" },
    ],
  },
  {
    id: "p3",
    name: "Agent Intelligence Pod",
    owner: "Marcus Webb",
    solutionType: "S3",
    initiatives: [
      { id: "i5", name: "Agent scoring consolidation", lastDemoDate: "2026-02-06", sliceDeadline: "2026-02-16", owner: "Marcus Webb", outcomeLinked: true, shipped: false, renewalAligned: true },
      { id: "i6", name: "Agent Trust Index definition", sliceDeadline: "2026-02-25", owner: "Yuki Tanaka", outcomeLinked: true, shipped: false, renewalAligned: false },
    ],
  },
  {
    id: "p4",
    name: "GTM & Positioning Pod",
    owner: "Alex Torres",
    solutionType: "Cross-Solution",
    initiatives: [
      { id: "i7", name: "S1→S2 renewal narrative", lastDemoDate: "2026-02-04", sliceDeadline: "2026-02-17", owner: "Alex Torres", outcomeLinked: true, shipped: false, renewalAligned: true, crossSolutionDep: "DPI Platform Pod" },
      { id: "i8", name: "VDPI bridge positioning", sliceDeadline: "2026-02-20", owner: "James Liu", outcomeLinked: false, shipped: false, renewalAligned: false },
    ],
  },
];

export const closedDecisions: ClosedDecision[] = [
  {
    id: "cd1",
    decisionId: "d-old-1",
    title: "Reduce QoE alert noise for enterprise streaming operators",
    expectedOutcome: "Reduce false alert volume by 60% while maintaining SLA coverage",
    actualResult: "Alert noise reduced 52% — partial success, SLA coverage maintained",
    segmentShift: "Enterprise streaming ops satisfaction +14pts",
    notes: "Threshold recalibration had largest impact. Remaining 8% gap requires ML-based filtering in next phase.",
    closedDate: "2026-01-20",
    solutionType: "S1",
    renewalImpact: "$2.8M renewal secured with improved operator experience",
    predictionAccuracy: "Partial",
  },
  {
    id: "cd2",
    decisionId: "d-old-2",
    title: "Restructure Agent Outcome reporting by enterprise segment",
    expectedOutcome: "Improve agent outcome clarity for enterprise buyers — reduce escalation by 30%",
    actualResult: "Enterprise escalation reduced 35%, mid-market unchanged",
    agentImpact: "Agent specialization reduced false escalation rate by 35%",
    segmentShift: "Enterprise confidence +12pts, mid-market flat",
    notes: "Mid-market requires dedicated DPI integration layer. Enterprise restructure exceeded targets.",
    closedDate: "2026-01-15",
    solutionType: "S3",
    renewalImpact: "Contributed to $3.1M enterprise renewal cycle",
    predictionAccuracy: "Accurate",
  },
  {
    id: "cd3",
    decisionId: "d-old-3",
    title: "Launch DPI behavioral pattern library for product leaders",
    expectedOutcome: "Achieve 40% adoption among target product leader accounts within 60 days",
    actualResult: "28% adoption — missed target due to onboarding friction",
    notes: "Product leaders valued the patterns but onboarding required too much custom configuration. Self-serve needed.",
    closedDate: "2026-01-08",
    solutionType: "S2",
    renewalImpact: "Indirect — positioned DPI for Q2 expansion conversations",
    predictionAccuracy: "Missed",
  },
];
