create table if not exists public.product_events (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  org_id uuid null references public.organizations(id) on delete cascade,
  user_id uuid null references auth.users(id) on delete set null,
  event_name text not null,
  route text null,
  source text not null default 'web',
  severity text not null default 'info' check (severity in ('info', 'warn', 'error')),
  session_id text null,
  metadata jsonb not null default '{}'::jsonb
);

create index if not exists product_events_org_created_idx on public.product_events (org_id, created_at desc);
create index if not exists product_events_name_created_idx on public.product_events (event_name, created_at desc);
create index if not exists product_events_severity_created_idx on public.product_events (severity, created_at desc);

alter table public.product_events enable row level security;

drop policy if exists "Members can insert product events" on public.product_events;
create policy "Members can insert product events"
on public.product_events
for insert
to authenticated
with check (
  org_id is null
  or exists (
    select 1
    from public.organization_memberships m
    where m.org_id = product_events.org_id
      and m.user_id = auth.uid()
  )
);

drop policy if exists "Members can read org product events" on public.product_events;
create policy "Members can read org product events"
on public.product_events
for select
to authenticated
using (
  org_id is not null
  and exists (
    select 1
    from public.organization_memberships m
    where m.org_id = product_events.org_id
      and m.user_id = auth.uid()
  )
);
